version: '3.8'

services:
  postgres-db:
    image: postgres:16
    container_name: trabalho_lpoo_db
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_ADMIN_PASSWORD:-1234}

      POSTGRES_DB: trabalho_lpoo
    
    ports:
      - "5432:5432"
      
    volumes:
      #- ./init-db:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: